### ISSUE TITLE
Array as a number?

### ISSUE THREAD

**Issue by dy** [CanadaHonk/porffor#1]
Hey, that's cool project.

I'd like to share an insight from [lino](https://github.com/audio-lab/lino) if you don't mind.

> everything is a number

So, arrays can be also represented as f64: int part of f64 allows storing up to i24 for memory address, and array length can be stored in fractional part as reinterpreted i32. From JS side array would be a pointer to memory: `let {ptr, memory} = instance.exports; let arr = new Float64Array(ptr, /* manual length or retrieved from pointer fractional part */)`

**Comment by CanadaHonk** [comment]
Hi, sorry completely missed this issue. lino looks cool! We have arrays now (since a few days ago) 🎉 via having arrays as a number which points to a page (address = `(1 + arrayNumber) * PageSize`) in Wasm linear memory and the length as a separate local. It would be interesting to store both (pointer and length) inside one f64 although I'm not sure the perf/mem tradeoffs of using two separate f64s (treated more like i32s though) instead.

![image](https://github.com/CanadaHonk/porffor/assets/19228318/1386a964-de13-4e06-8f45-f12758e5bf2b)

**Comment by dy** [comment]
Cool. So you allocate 1 page per array?

**Comment by dy** [comment]
64KiB is 8192 f64 elements, right?

**Comment by CanadaHonk** [comment]
Yeah, not sure why I said 1024 earlier haha, meant that.

**Comment by dy** [comment]
I mean 1024 x 64, so makes sense, I got confused myself for a bit.
